STORE_APP/STORE_APP/Models/Entity/CARS_INFORMATION.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CARS_INFORMATION
    {
        [Required(ErrorMessage = "Number Plate should not be empty")]
        public string CAR_NUMBER_PLATE { get; set; }
        [Required(ErrorMessage = "Information should not be empty")]
        public string INFORMATION { get; set; }
        public Nullable<System.DateTime> LAST_MAINTANCE_DATE { get; set; }
        public Nullable<System.DateTime> NEXT_MAINTANCE_DATE { get; set; }
        [Required(ErrorMessage = "Activity should not be empty")]
        [Range(0, 1, ErrorMessage = "Activity should not be 0,1")]
        public Nullable<int> IS_ACTIV { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        [Required(ErrorMessage = "Kilometer should not be empty")]
        public Nullable<int> KILOMETER { get; set; }
        public int CAR_INFORMATION_ID { get; set; }
        [Required(ErrorMessage = "Shassis Code should not be empty")]
        public string CAR_SHASSIS_CODE { get; set; }
    }
}

STORE_APP/STORE_APP/Controllers/Cars_Information_Controller.cs
using Newtonsoft.Json.Linq;
using STORE_APP.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using System.Linq;


namespace STORE_APP.Controllers
{
    public class Cars_Information_Controller : Controller
    {
        DB_STORE_APPEntities1 db = new DB_STORE_APPEntities1();
        // GET: Cars_Information_
        public ActionResult Index(String p)
        {

            var values = from k in db.CARS_INFORMATION select k;
            if (!string.IsNullOrEmpty(p))
            {
                values = values.Where(m => m.CAR_NUMBER_PLATE.Contains(p));
            }
            return View(values.ToList());
        }

        [HttpGet]
        public ActionResult Add_Car_Information()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add_Car_Information(CARS_INFORMATION value)
        {
            if (!ModelState.IsValid)
            {
                return View("Add_Car_Information");
            }
            db.CARS_INFORMATION.Add(value);          
            db.SaveChanges();
            return RedirectToAction("index");
        }

        ////Delete Car Category with Id
        //public ActionResult Delete_Car_Information(int id)
        //{
        //    var value = db.CARS_INFORMATION.Find(id);
        //    db.CARS_INFORMATION.Remove(value);
        //    db.SaveChanges();
        //    return RedirectToAction("index");
        //}

        //connected Update_Department View for find department with id
        public ActionResult Update_Car_Information_View(string id)
        {
            var value = db.CARS_INFORMATION.Find(id);
            return View("Update_Car_Information_View", value);
        }

        //update department
        public ActionResult Update_Car_Information(CARS_INFORMATION p)
        {
            if (!ModelState.IsValid)
            {
                return View("Update_Car_Information_View");
            }
            var information = db.CARS_INFORMATION.Find(p.CAR_INFORMATION_ID);
            // string d = Update_Car_Information_View(); ; 
            information.INFORMATION = p.INFORMATION;
            information.CAR_SHASSIS_CODE = p.CAR_SHASSIS_CODE;
            information.CAR_NUMBER_PLATE = p.CAR_NUMBER_PLATE;
            information.LAST_MAINTANCE_DATE = p.LAST_MAINTANCE_DATE;
            information.NEXT_MAINTANCE_DATE = p.NEXT_MAINTANCE_DATE;
            information.IS_ACTIV = p.IS_ACTIV;
            information.KILOMETER = p.KILOMETER;
            information.C_DATE = p.U_DATE;
            
            //department.IS_ACTIV = p.IS_ACTIV;
            db.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult Max_Use_Car()
        {
            var query = from cc in db.CARS_CATEGORY
                        join c in db.CARS on cc.CAR_CATEGORY_ID equals c.CAR_CATEGORY_ID
                        join sh in db.SALES_HISTORY on c.CAR_ID equals sh.CAR_ID
                        where cc.IS_ACTIV == 1
                        group sh by cc.CAR_CATEGORY_NAME into g
                        select new MaxUseCarResult
                        {
                            CarCategoryName = g.Key,
                            NumberOfSales = g.Count()
                        };
            var result = query.OrderByDescending(g => g.NumberOfSales).ToList();
            return View("Max_Use_Car",result);
        }

        public class MaxUseCarResult
        {
            public string CarCategoryName { get; set; }
            public int NumberOfSales { get; set; }
        }

        public ActionResult MaintenanceDueCars()
        {
            var currentDate = DateTime.Now;

            var query = from ci in db.CARS_INFORMATION
                        where ci.NEXT_MAINTANCE_DATE <= currentDate && ci.IS_ACTIV == 1
                        select new MaintenanceDueCarViewModel
                        {
                            CarNumberPlate = ci.CAR_NUMBER_PLATE,
                            LastMaintenanceDate = ci.LAST_MAINTANCE_DATE,
                            NextMaintenanceDate = ci.NEXT_MAINTANCE_DATE
                        };

            var result = query.ToList();

            return View("MaintenanceDueCars", result);
        }
        public class MaintenanceDueCarViewModel
        {
            public string CarNumberPlate { get; set; }
            public DateTime? LastMaintenanceDate { get; set; }
            public DateTime? NextMaintenanceDate { get; set; }
        }
    }
}

STORE_APP/STORE_APP/Views/Cars_Information_/Add_Car_Information.cshtml
@model STORE_APP.Models.Entity.CARS_INFORMATION


@{
    ViewBag.Title = "Add_Car_Informatıon";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2><strong>CAR INFORMATION</strong></h2>

<form class="form-group" method="post">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- jQuery UI (Including datepicker) -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <div></div>
    @* Car Category Id *@
    <div style="margin-top:15px">
        <label>SHASSIS CODE</label>
        @Html.TextBoxFor(car => car.CAR_SHASSIS_CODE, new { @class = "form-control" })
        @Html.ValidationMessageFor(car => car.CAR_SHASSIS_CODE, "", new { @style = "color:red" })
    </div>
    @* Car Shassis Code *@
    <div style="margin-top:15px">
        <label>NUMBER PLATE</label>
        @Html.TextBoxFor(car => car.CAR_NUMBER_PLATE, new { @class = "form-control" })
        @Html.ValidationMessageFor(car => car.CAR_NUMBER_PLATE, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>KILOMETER</label>
        @Html.TextBoxFor(car => car.KILOMETER, new { @class = "form-control" })
        @Html.ValidationMessageFor(car => car.KILOMETER, "", new { @style = "color:red" })
    </div>
    @* INFORMATION *@
    <div style="margin-top:15px">
        <label>Information</label>
        @Html.TextBoxFor(car => car.INFORMATION, new { @class = "form-control" })
        @Html.ValidationMessageFor(car => car.INFORMATION, "", new { @style = "color:red" })
    </div>
    @* LAST_MAINTANCE_DATE *@
    <div style="margin-top:15px">
        <label>LAST MAINTANCE DATE</label>
        <input type="text" id="datepicker" class="form-control" name="LAST_MAINTANCE_DATE"
               value="@DateTime.Now.ToShortDateString()" />
        <script>
            $(function () {
                $("#datepicker").datepicker();
            });
        </script>
    </div>
    <div style="margin-top:15px">
        <label>NEXT MAINTANCE DATE</label>
        <input type="text" id="datepicker1" class="form-control" name="NEXT_MAINTANCE_DATE"
               value="@DateTime.Now.ToShortDateString()" />
        <script>
            $(function () {
                $("#datepicker1").datepicker();
            });
        </script>
    </div>
    <div style="margin-top:15px">
        <datalist id="Activity">
            <option value="1">
            <option value="0">
        </datalist>
        <label>Activity</label>
        <input type="text" class="form-control" name="IS_ACTIV"
               list="Activity" />
        @Html.ValidationMessageFor(x => x.IS_ACTIV, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>C Date</label>
        <input type="text" id="datepicker2" class="form-control" name="C_DATE"
               value="@DateTime.Now.ToShortDateString()" />
        <script>
            $(function () {
                $("#datepicker2").datepicker();
            });
        </script>
    </div>
    @* Add Car Button *@
    <div style="margin-top:15px">
        <button class="btn btn-info">Add Car Information</button>
    </div>


</form>

STORE_APP/STORE_APP/Views/Cars_Information_/Index.cshtml
@using STORE_APP.Models.Entity;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2><strong>Car Information</strong></h2>
@using (Html.BeginForm("Index", "Cars_Information_", FormMethod.Get))
{
    <div style="margin-top;15px; margin-bottom:15px;">
        <b>Number Plate: &nbsp</b>@Html.TextBox("p")
        <input type="submit" value="Search"
    </div>

}
<div style="margin-top;15px; margin-bottom:15px;">
    <table class="table table-bordered">
        <div style="margin-top;15px; margin-bottom:15px;">
        <tr>
            @* Create Table *@
            <th>CAR SHASIS CODE</th>
            <th>Car Number Plate</th>
            <th>Information</th>
            <th>Last Maıntance Date</th>
            <th>Next Maıntance Date</th>
            <th>C_Date</th>
            <th>U_Date</th>
            <th>Update</th>
        </tr>
        @* Get Date *@
        @foreach (var car in Model)
        {
            <tr>
                @* Get Date For Table *@
                <td>@car.CAR_SHASSIS_CODE</td>
                <td>@car.CAR_NUMBER_PLATE</td>
                <td>@car.INFORMATION</td>
                <td>@Convert.ToDateTime(car.LAST_MAINTANCE_DATE).ToString("dd/MM/yyyy")</td>
                <td>@Convert.ToDateTime(car.NEXT_MAINTANCE_DATE).ToString("dd/MM/yyyy")</td>
                <td>@Convert.ToDateTime(car.C_DATE).ToString("dd/MM/yyyy")</td>
                <td>@Convert.ToDateTime(car.U_DATE).ToString("dd/MM/yyyy")</td>
                <td><a href="/Cars_Information_/Update_Car_Information_View/@car.CAR_NUMBER_PLATE" class="btn btn-success">Update</a></td>
            </tr>
        }
    </table>
    <a href="/Cars_Information_/Add_Car_Information/" class="btn btn-primary">Add New Car Information</a>

STORE_APP/STORE_APP/Views/Cars_Information_/MaintenanceDueCars.cshtml
@{
    ViewBag.Title = "MaintenanceDueCars";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<h2><strong>Vehicles Malfunctions</strong></h2>
<div style="margin-top;15px; margin-bottom:15px;">
    <table class="table table-bordered">
        <div style="margin-top;15px; margin-bottom:15px;" />
        <tr>
            @* Create Table *@
            <th>Number Plate </th>
            <th>Last Maintenance Date</th>
            <th>Next Maintenance Date</th>
        </tr>
        @* Get Date *@

        @foreach (var car in Model)
        {
            <tr>
                @* Get Date For Table *@
                <td>@car.CarNumberPlate</td>
                <td>@Convert.ToDateTime(car.LastMaintenanceDate).ToString("dd/MM/yyyy")</td>
                <td>@Convert.ToDateTime(car.NextMaintenanceDate).ToString("dd/MM/yyyy")</td>
            </tr>
        }
    </table>
</div>

STORE_APP/STORE_APP/Views/Cars_Information_/Max_Use_Car.cshtml
@using STORE_APP.Models.Entity;
@{
    ViewBag.Title = "Update_Car_Information_View";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!DOCTYPE html>

@*@using (Html.BeginForm("Max_Use_Car", "Cars_Information_", FormMethod.Get)) {*@
<div style="margin-top;15px; margin-bottom:15px;">
    <table class="table table-bordered">
        <div style="margin-top;15px; margin-bottom:15px;" />
        <tr>
            @* Create Table *@
            <th>CAR_CATEGORY_NAME </th>
            <th>Value</th>
        </tr>
        @* Get Date *@

        @foreach (var car in Model)
        {
            <tr>
                @* Get Date For Table *@
                <td>@car.CarCategoryName</td>
                <td>@car.NumberOfSales</td>
            </tr>
        }
    </table>
</div>
@*}*@

STORE_APP/STORE_APP/Views/Cars_Information_/Update_Car_Information_View.cshtml
@model STORE_APP.Models.Entity.CARS_INFORMATION
@{
    ViewBag.Title = "Update_Car_Information_View";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Update_Car_Information_View</h2>

@*                      ActionResult         Controller *@
@using (Html.BeginForm("Update_Car_Information", "Cars_Information_", FormMethod.Post))
{

    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <!-- jQuery UI (Including datepicker) -->
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <div></div>
        @* Car Category Id *@
        @Html.LabelFor(k => k.CAR_INFORMATION_ID)
        @Html.TextBoxFor(k => k.CAR_INFORMATION_ID, new { @class = "form-control" })
        <div style="margin-top:15px">
            <label>SHASSIS CODE</label>
            @Html.TextBoxFor(car => car.CAR_SHASSIS_CODE, new { @class = "form-control" })
            @Html.ValidationMessageFor(car => car.CAR_SHASSIS_CODE, "", new { @style = "color:red" })
        </div>
        @* Car Shassis Code *@
        <div style="margin-top:15px">
            <label>NUMBER PLATE</label>
            @Html.TextBoxFor(car => car.CAR_NUMBER_PLATE, new { @class = "form-control" })
            @Html.ValidationMessageFor(car => car.CAR_NUMBER_PLATE, "", new { @style = "color:red" })
        </div>
        <div style="margin-top:15px">
            <label>KILOMETER</label>
            @Html.TextBoxFor(car => car.KILOMETER, new { @class = "form-control" })
            @Html.ValidationMessageFor(car => car.KILOMETER, "", new { @style = "color:red" })
        </div>
        @* INFORMATION *@
        <div style="margin-top:15px">
            <label>Information</label>
            @Html.TextBoxFor(car => car.INFORMATION, new { @class = "form-control" })
            @Html.ValidationMessageFor(car => car.INFORMATION, "", new { @style = "color:red" })
        </div>
        @* LAST_MAINTANCE_DATE *@
        <div style="margin-top:15px">
            <label>LAST MAINTANCE DATE</label>
            <input type="text" id="datepicker" class="form-control" name="LAST_MAINTANCE_DATE"
                   value="@DateTime.Now.ToShortDateString()" />
            <script>
                $(function () {
                    $("#datepicker").datepicker();
                });
            </script>
        </div>
        <div style="margin-top:15px">
            <label>NEXT MAINTANCE DATE</label>
            <input type="text" id="datepicker1" class="form-control" name="NEXT_MAINTANCE_DATE"
                   value="@DateTime.Now.ToShortDateString()" />
            <script>
                $(function () {
                    $("#datepicker1").datepicker();
                });
            </script>
        </div>
        <div style="margin-top:15px">
            <datalist id="Activity">
                <option value="1">
                <option value="0">
            </datalist>
            <label>Activity</label>
            <input type="text" class="form-control" name="IS_ACTIV"
                   list="Activity" />
            @Html.ValidationMessageFor(x => x.IS_ACTIV, "", new { @style = "color:red" })
        </div>
        <div style="margin-top:15px">
            <label>C Date</label>
            <input type="text" id="datepicker2" class="form-control" name="U_DATE"
                   value="@DateTime.Now.ToShortDateString()" />
            <script>
                $(function () {
                    $("#datepicker2").datepicker();
                });
            </script>
        </div>
    </div>
    <div><button class="btn btn-warning">Update</button></div>
}