STORE_APP/STORE_APP/Models/Entity/CARS_CATEGORY.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CARS_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARS_CATEGORY()
        {
            this.APPOINTMENT = new HashSet<APPOINTMENT>();
            this.CARS = new HashSet<CARS>();
        }

        public int CAR_CATEGORY_ID { get; set; }
        [Required(ErrorMessage = "Category should not be empty")]
        public string CAR_CATEGORY_NAME { get; set; }
        [Required(ErrorMessage = "Activity should not be empty")]
        [Range(0, 1, ErrorMessage = "Activity should not be 0,1")]
        public Nullable<int> IS_ACTIV { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        public string CAR_IMG { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARS> CARS { get; set; }
    }

}

STORE_APP/STORE_APP/Controllers/Cars_Category_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using STORE_APP.Models.Entity;

namespace STORE_APP.Controllers
{
    public class Cars_Category_Controller : Controller
    {

        DB_STORE_APPEntities1 db = new DB_STORE_APPEntities1();
        // GET: Cars_Category_ Table Values List
        public ActionResult Index()
        {
            var values = db.CARS_CATEGORY.ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult Add_Category()
        {       
            return View();
        }
        //Add New Car Category For Click Button
        [HttpPost]
        public ActionResult Add_Category(CARS_CATEGORY value)
        {
            if (!ModelState.IsValid)
            {
                return View("Add_Category");
            }
            db.CARS_CATEGORY.Add(value);
            db.SaveChanges();
            return RedirectToAction("index");
        }

        //Delete Car Category with Id
        public ActionResult Delete_Category(int id)
        {
            var category = db.CARS_CATEGORY.Find(id);
            db.CARS_CATEGORY.Remove(category);
            db.SaveChanges();
            return RedirectToAction("index");
        }

        //connected Update_Category View for find category with id
        public ActionResult Update_Category_View(int id)
        {
            var ctg = db.CARS_CATEGORY.Find(id);
            return View("Update_Category_View", ctg);
        }

        //update category
        public ActionResult Update_Category(CARS_CATEGORY p)
        {
            if (!ModelState.IsValid)
            {
                return View("Update_Category_View");
            }
            var ctg = db.CARS_CATEGORY.Find(p.CAR_CATEGORY_ID);
            ctg.CAR_CATEGORY_NAME = p.CAR_CATEGORY_NAME;
            ctg.IS_ACTIV = p.IS_ACTIV;
            ctg.CAR_IMG = p.CAR_IMG;
            ctg.U_DATE  = p.U_DATE;
            db.SaveChanges();
            return RedirectToAction("index");
        }

    }
}

STORE_APP/STORE_APP/Views/Cars_Category_/Add_Category.cshtml
@model STORE_APP.Models.Entity.CARS_CATEGORY
@{
    ViewBag.Title = "Add_Category";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- jQuery UI (Including datepicker) -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


    @* Car Category Name *@
<div style="margin-top:15px;">
    <label>Category Name</label>
    @Html.TextBoxFor(x => x.CAR_CATEGORY_NAME, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CAR_CATEGORY_NAME, "", new { @style = "color:red" })
</div>
    <div style="margin-top:15px;">
        <label>Image Link</label>
        <input type="text" class="form-control" name="CAR_IMG" />
    </div>
    @* Category Activity *@
    <div style="margin-top:15px">
        <datalist id="Activity">
            <option value="1">
            <option value="0">
        </datalist>
        <label>Activity</label>
        <input type="text" class="form-control" name="IS_ACTIV"
               list="Activity" />
        @Html.ValidationMessageFor(x => x.IS_ACTIV, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>DATE</label>
        <input type="text" id="datepicker" class="form-control" name="C_DATE"
               value="@DateTime.Now.ToShortDateString()" />
        <script>
            $(function () {
                $("#datepicker").datepicker({ dateFormat: "dd/mm/yy" });
            });
        </script>
    </div>


    <div style="margin-top:15px">
        <button class=" btn btn-info" id="btn_Add">Add Category</button>
    </div>
</form>

STORE_APP/STORE_APP/Views/Cars_Category_/Index.cshtml
@using STORE_APP.Models.Entity;
    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/Layout.cshtml";
    }

    <h2><strong>Car Category</strong></h2>

    <table class="table table-bordered">
        <tr>
            @* Create Table *@
            <th>Category Id</th>
            <th>Category Name</th>
            <th>Image Link</th>
            <th>Activity</th>
            <th>C_Date</th>
            <th>U_Date</th>
            <th>Delete</th>
            <th>Update</th>
        </tr>
        @* Get Date *@
        @foreach (var ctg in Model)
        {
            <tr>
                @* Get Date For Table *@
                <td>@ctg.CAR_CATEGORY_ID</td>
                <td>@ctg.CAR_CATEGORY_NAME</td>
                <td>@ctg.CAR_IMG</td>
                <td>@ctg.IS_ACTIV</td>
                <td>@Convert.ToDateTime(ctg.C_DATE).ToString("dd/MM/yyyy")</td>
                <td>@Convert.ToDateTime(ctg.U_DATE).ToString("dd/MM/yyyy")</td>            
                <td>@Html.ActionLink("Delete", "Delete_Category", new { id = ctg.CAR_CATEGORY_ID }, new { @class = "btn btn-danger", onclick = "return confirm('Do you want delete this category?')" })</td>
                <td><a href="/Cars_Category_/Update_Category_View/@ctg.CAR_CATEGORY_ID" class="btn btn-success">Update</a></td>
            </tr>
        }
    </table>
    <a href="/Cars_Category_/Add_Category" class="btn btn-primary">Add New Category</a>

STORE_APP/STORE_APP/Views/Cars_Category_/Update_Category_View.cshtml
@{
    ViewBag.Title = "Update_Category_View";
    Layout = "~/Views/Shared/Layout.cshtml";
}


@model STORE_APP.Models.Entity.CARS_CATEGORY
    @*                  ActionResult        Controller *@
@using (Html.BeginForm("Update_Category", "Cars_Category_", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <!-- jQuery UI (Including datepicker) -->
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

        @Html.LabelFor(k => k.CAR_CATEGORY_ID)
        @Html.TextBoxFor(k => k.CAR_CATEGORY_ID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(k => k.CAR_CATEGORY_NAME)
        @Html.TextBoxFor(k => k.CAR_CATEGORY_NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CAR_CATEGORY_NAME, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(k => k.CAR_IMG)
        @Html.TextBoxFor(k => k.CAR_IMG, new { @class = "form-control" })
        <div>
            <datalist id="Activity">
                <option value="1">
                <option value="0">
            </datalist>
            <label>Activity</label>
            <input type="text" class="form-control" name="IS_ACTIV"
                   list="Activity" />
            @Html.ValidationMessageFor(x => x.IS_ACTIV, "", new { @style = "color:red" })
        </div>
        <div style="margin-top:15px">
            <label>DATE</label>
            <input type="text" id="datepicker" class="form-control" name="U_DATE"
                   value="@DateTime.Now.ToShortDateString()" />
            <script>
                $(function () {
                    $("#datepicker").datepicker({ dateFormat: "dd/mm/yy" });
                });
            </script>
        </div>
    </div>
    <div><button class="btn btn-warning">Update</button></div>
}