STORE_APP/STORE_APP/Models/Entity/CUSTOMERS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CUSTOMERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMERS()
        {
            this.APPOINTMENT = new HashSet<APPOINTMENT>();
            this.SALES_HISTORY = new HashSet<SALES_HISTORY>();
        }

        public int CUSTOMER_ID { get; set; }
        [Required(ErrorMessage = "Name should not be empty")]
        public string NAME { get; set; }
        [Required(ErrorMessage = "Surname should not be empty")]
        public string SURNAME { get; set; }
        [Required(ErrorMessage = "Phone should not be empty")]
        public string PHONE { get; set; }
        [Required(ErrorMessage = "E-Mail should not be empty")]
        public string EMAIL { get; set; }
        public string COMPANY_NAME { get; set; }
        [Required(ErrorMessage = "Activity should not be empty")]
        [Range(0, 1, ErrorMessage = "Activity should not be 0,1")]
        public Nullable<int> IS_ACTIV { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        [Required(ErrorMessage = "Password should not be empty")]
        public string PASSWORD { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_HISTORY> SALES_HISTORY { get; set; }
    }

}

STORE_APP/STORE_APP/Controllers/Customers_Controller.cs
using STORE_APP.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace STORE_APP.Controllers
{
    public class Customers_Controller : Controller
    {
        DB_STORE_APPEntities1 db = new DB_STORE_APPEntities1();
        // GET: Customers_
        public ActionResult Index(string p)
        {
            var values = from k in db.CUSTOMERS select k;
            if (!string.IsNullOrEmpty(p))
            {
                values = values.Where(m => m.EMAIL.Contains(p));
            }
            return View(values.ToList());
        }

        [HttpGet]
        public ActionResult Add_Customers()
        {
            return View();
        }
        //Add New Departments For Click Button
        [HttpPost]
        public ActionResult Add_Customers(CUSTOMERS value)
        {
            if (!ModelState.IsValid)
            {
                return View("Add_Customers");
            }
            db.CUSTOMERS.Add(value);
            db.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult Delete_Customer(int id)
        {
            var department = db.CUSTOMERS.Find(id);
            if(department.IS_ACTIV==0) {
                department.IS_ACTIV = 1;
            }
            else if(department.IS_ACTIV==1) {
                department.IS_ACTIV = 0;
            }
            db.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult Update_Customer_View(int id)
        {
            var customer = db.CUSTOMERS.Find(id);
            return View("Update_Customer_View", customer);
        }

        //update department
        public ActionResult Update_Customer(CUSTOMERS p)
        {
            if (p.NAME==null || p.SURNAME == null || p.EMAIL ==null || p.PASSWORD == null || p.PHONE == null)
            {
                return View("Update_Customer_View");
            }
            var customer = db.CUSTOMERS.Find(p.CUSTOMER_ID);
            customer.NAME = p.NAME;
            customer.EMAIL = p.EMAIL; 
            customer.SURNAME = p.SURNAME;
            customer.COMPANY_NAME = p.COMPANY_NAME; 
            customer.PHONE = p.PHONE;
            customer.PASSWORD = p.PASSWORD;
            customer.U_DATE = p.U_DATE;
            db.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult Update_Customer_View_For_Customer()
        {
            int customer_id =Convert.ToInt32(Session["customer_id"]);
            var customer = db.CUSTOMERS.Find(customer_id);
            return View("Update_Customer_View_For_Customer", customer);
        }

        //update department
        public ActionResult Update_Customer_For_Customer(CUSTOMERS p)
        {
            if (p.NAME == null || p.SURNAME == null || p.EMAIL == null || p.PASSWORD == null || p.PHONE == null)
            {
                return View("Update_Customer_View_For_Customer");
            }
            var customer = db.CUSTOMERS.Find(p.CUSTOMER_ID);
            customer.NAME = p.NAME;
            customer.EMAIL = p.EMAIL;
            customer.SURNAME = p.SURNAME;
            customer.COMPANY_NAME = p.COMPANY_NAME;
            customer.PHONE = p.PHONE;
            customer.PASSWORD = p.PASSWORD;
            customer.U_DATE = p.U_DATE;
            db.SaveChanges();
            return RedirectToAction("Update_Customer_View_For_Customer");
        }
    }
}

STORE_APP/STORE_APP/Views/Customers_/Add_Customers.cshtml
@{
    ViewBag.Title = "Add_Customers";
    Layout = "~/Views/Shared/Layout.cshtml";
}
@model STORE_APP.Models.Entity.CUSTOMERS
<form class="form-group" method="post">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- jQuery UI (Including datepicker) -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    @* Car Category Name *@
    <div style="margin-top:15px;">
        <label>Name</label>
        @*<input type="text" class="form-control" name="DEPARTMENT_NAME" />*@
        @Html.TextBoxFor(x => x.NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.NAME, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px;">
        <label>Surname</label>
        @*<input type="text" class="form-control" name="DEPARTMENT_NAME" />*@
        @Html.TextBoxFor(x => x.SURNAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.SURNAME, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px;">
        <label>Phone</label>
        @*<input type="text" class="form-control" name="DEPARTMENT_NAME" />*@
        @Html.TextBoxFor(x => x.PHONE, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PHONE, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px;">
        <label>E-Mail</label>
        @*<input type="text" class="form-control" name="DEPARTMENT_NAME" />*@
        @Html.TextBoxFor(x => x.EMAIL, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.EMAIL, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px;">
        <label>Company Name</label>
        @*<input type="text" class="form-control" name="DEPARTMENT_NAME" />*@
        @Html.TextBoxFor(x => x.COMPANY_NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.COMPANY_NAME, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px;">
        <label>Password</label>
        @*<input type="text" class="form-control" name="DEPARTMENT_NAME" />*@
        @Html.TextBoxFor(x => x.PASSWORD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PASSWORD, "", new { @style = "color:red" })
    </div>
    @* Category Activity *@
    <div style="margin-top:15px">
        <datalist id="Activity">
            <option value="1">
            <option value="0">
        </datalist>
        <label>Activity</label>
        <input type="text" class="form-control" name="IS_ACTIV"
               list="Activity" />
        @Html.ValidationMessageFor(x => x.IS_ACTIV, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>DATE</label>
        <input type="text" id="datepicker" class="form-control" name="C_DATE"
               value="@DateTime.Now.ToShortDateString()" />
        <script>
            $(function () {
                $("#datepicker").datepicker({ dateFormat: "dd/mm/yy" });
            });
        </script>
    </div>

    <div style="margin-top:15px">
        <button class=" btn btn-info" id="btn_Add">Add Customer</button>
    </div>
</form>

STORE_APP/STORE_APP/Views/Customers_/Index.cshtml
@using STORE_APP.Models.Entity;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2><strong>Customers</strong></h2>

<table class="table table-bordered">
    <tr>
        @* Create Table *@
        <th>Customer Id</th>
        <th>Name</th>
        <th>Phone</th>
        <th>E-Mail</th>
        <th>Company Name</th>
        <th>Password</th>
        <th>Activity</th>
        <th>C_DATE</th>
        <th>U_DATE</th>
        <th>Activity Button</th>
        <th>Update</th>
    </tr>
    @* Get Date *@
    @foreach (var customer in Model)
    {
        <tr>
            @* Get Date For Table *@
            <td>@customer.CUSTOMER_ID</td>
            <td>@customer.NAME @customer.SURNAME</td>
            <td>@customer.PHONE</td>
            <td>@customer.EMAIL</td>
            <td>@customer.COMPANY_NAME</td>
            <td>@customer.PASSWORD</td>
            <td>@customer.IS_ACTIV</td>
            <td>@Convert.ToDateTime(customer.C_DATE).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(customer.U_DATE).ToString("dd/MM/yyyy")</td>
            <td>@Html.ActionLink("Activity Button", "Delete_Customer", new { id = customer.CUSTOMER_ID , }, new { @class = "btn btn-warning", onclick = "return confirm('Do you want change activity this customer?')" })</td>
            @*<td><a href="/Departments_/Delete_Department/@ctg.DEPARTMENT_ID" class="btn btn-danger">Delete</a></td>*@
            <td><a href="/Customers_/Update_Customer_View/@customer.CUSTOMER_ID" class="btn btn-success">Update</a></td>
        </tr>
    }
</table>
<a href="/Customers_/Add_Customers" class="btn btn-primary">Add New Customer</a>

STORE_APP/STORE_APP/Views/Customers_/Update_Customer_View.cshtml
@model STORE_APP.Models.Entity.CUSTOMERS
@{
    ViewBag.Title = "Update_Customer_View";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@*                      ActionResult         Controller *@
@using (Html.BeginForm("Update_Customer", "Customers_", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <!-- jQuery UI (Including datepicker) -->
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

        @Html.LabelFor(k => k.CUSTOMER_ID)
        @Html.TextBoxFor(k => k.CUSTOMER_ID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(k => k.NAME)
        @Html.TextBoxFor(k => k.NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.NAME, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(k => k.SURNAME)
        @Html.TextBoxFor(k => k.SURNAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.SURNAME, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(k => k.PHONE)
        @Html.TextBoxFor(k => k.PHONE, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PHONE, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(k => k.EMAIL)
        @Html.TextBoxFor(k => k.EMAIL, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.EMAIL, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(k => k.COMPANY_NAME)
        @Html.TextBoxFor(k => k.COMPANY_NAME, new { @class = "form-control" })
        <br />
        @Html.LabelFor(k => k.PASSWORD)
        @Html.TextBoxFor(k => k.PASSWORD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PASSWORD, "", new { @style = "color:red" })
        <div style="margin-top:15px">
            <label>DATE</label>
            <input type="text" id="datepicker" class="form-control" name="U_DATE"
                   value="@DateTime.Now.ToShortDateString()" />
            <script>
                $(function () {
                    $("#datepicker").datepicker({ dateFormat: "dd/mm/yy" });
                });
            </script>
        </div>
    </div>
    <div><button class="btn btn-warning">Update</button></div>
}

STORE_APP/STORE_APP/Views/Customers_/Update_Customer_View_For_Customer.cshtml
@model STORE_APP.Models.Entity.CUSTOMERS
@{
    ViewBag.Title = "Update_Customer_View_For_Customer";
    Layout = "~/Views/Shared/Customer_Layout.cshtml";
}

<h2>Edit Profile</h2>


@*                      ActionResult         Controller *@
@using (Html.BeginForm("Update_Customer_For_Customer", "Customers_", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <!-- jQuery UI (Including datepicker) -->
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        @Html.LabelFor(k => k.CUSTOMER_ID)
       @* @Html.TextBoxFor(k => k.CUSTOMER_ID, new { @class = "form-control" })*@
        @Html.TextBoxFor(model => model.CUSTOMER_ID, new { @class = "form-control", @id = "myInput", @disabled = "disabled", @value = "@Update_Customer_For_Customer" })
        <br />
        @Html.LabelFor(k => k.NAME)
        @Html.TextBoxFor(k => k.NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.NAME, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(k => k.SURNAME)
        @Html.TextBoxFor(k => k.SURNAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.SURNAME, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(k => k.PHONE)
        @Html.TextBoxFor(k => k.PHONE, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PHONE, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(k => k.EMAIL)
        @Html.TextBoxFor(k => k.EMAIL, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.EMAIL, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(k => k.COMPANY_NAME)
        @Html.TextBoxFor(k => k.COMPANY_NAME, new { @class = "form-control" })
        <br />
        @Html.LabelFor(k => k.PASSWORD)
        @Html.TextBoxFor(k => k.PASSWORD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PASSWORD, "", new { @style = "color:red" })
        <div style="margin-top:15px">
            <label>DATE</label>
            <input type="text" id="datepicker" class="form-control" name="U_DATE"
                   value="@DateTime.Now.ToShortDateString()" />
            <script>
                $(function () {
                    $("#datepicker").datepicker({ dateFormat: "dd/mm/yy" });
                });
            </script>
        </div>
    </div>
    <div><button class="btn btn-warning">Update</button></div>
}