STORE_APP/STORE_APP/Models/Entity/EMPLOYEES.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STORE_APP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EMPLOYEES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEES()
        {
            this.SALES_HISTORY = new HashSet<SALES_HISTORY>();
        }

        public int EMPLOYEE_ID { get; set; }
        public Nullable<int> DEPARTMENT_ID { get; set; }
        [Required(ErrorMessage = "Name should not be empty")]
        public string NAME { get; set; }
        [Required(ErrorMessage = "SurName should not be empty")]
        public string SURNAME { get; set; }
        public Nullable<System.DateTime> BIRT_DATE { get; set; }
        [Required(ErrorMessage = "Identity Number should not be empty")]
        public Nullable<int> IDENTIFY_NUMBER { get; set; }
        public Nullable<int> EMPLOYEE_POINT { get; set; }
        public Nullable<int> TOTAL_SERVICE { get; set; }
        [Required(ErrorMessage = "Activity should not be empty")]
        [Range(0, 1, ErrorMessage = "Activity should not be 0,1")]
        public Nullable<int> IS_ACTIV { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public Nullable<System.DateTime> U_DATE { get; set; }
        [Required(ErrorMessage = "Password should not be empty")]
        public string PASSWORD { get; set; }
        [Required(ErrorMessage = "E-Mail should not be empty")]
        public string EMAIL { get; set; }

        public virtual DEPARTMENTS DEPARTMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_HISTORY> SALES_HISTORY { get; set; }
    }
}

STORE_APP/STORE_APP/Controllers/Employees_Controller.cs
using STORE_APP.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace STORE_APP.Controllers
{
    public class Employees_Controller : Controller
    {
        DB_STORE_APPEntities1 db = new DB_STORE_APPEntities1();

        // GET: Employees_
        public ActionResult Index(String p)
        {
            var values = from k in db.EMPLOYEES select k;
            if (!string.IsNullOrEmpty(p))
            {
                values = values.Where(m => m.NAME.Contains(p));
            }
            return View(values.ToList());
           
        }

        [HttpGet]
        public ActionResult Add_Employee()
        {
            //car eklemek için car category ıd alanına car category isimlerini taşı
            List<SelectListItem> listCarCategory = (from i in db.DEPARTMENTS.ToList()
                                                    select new SelectListItem
                                                    {
                                                       
                                                        Text = i.DEPARTMENT_NAME,
                                                        Value =i.DEPARTMENT_ID.ToString()
                                                    }).ToList();
            //view'e taşı
            ViewBag.listCarCategoryView = listCarCategory;
            return View();
        }
        [HttpPost]
        public ActionResult Add_Employee(EMPLOYEES employee)
        {
            var value = db.DEPARTMENTS.Where(k => k.DEPARTMENT_ID == employee.DEPARTMENTS.DEPARTMENT_ID).FirstOrDefault();
            employee.DEPARTMENTS = value;
            if (employee.EMAIL ==null || employee.PASSWORD == null || employee.NAME == null || employee.SURNAME == null || employee.IDENTIFY_NUMBER == null ||(employee.IS_ACTIV != 0 && employee.IS_ACTIV !=1))
            {
                List<SelectListItem> listCarCategory = (from i in db.DEPARTMENTS.ToList()
                                                        select new SelectListItem
                                                        {

                                                            Text = i.DEPARTMENT_NAME,
                                                            Value = i.DEPARTMENT_ID.ToString()
                                                        }).ToList();
                //view'e taşı
                ViewBag.listCarCategoryView = listCarCategory;
                return View("Add_Employee");
            }
            employee.TOTAL_SERVICE = 0;
            db.EMPLOYEES.Add(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Delete Car with Id
        public ActionResult Delete_Employee(int id)
        {
            var employee = db.EMPLOYEES.Find(id);
            db.EMPLOYEES.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("index");
        }

        //connected Update_Car View for find car with id
        public ActionResult Update_Employee_View(int id)
        {
            var employee = db.CARS.Find(id);
            //car eklemek için car category ıd alanına car category isimlerini taşı
            List<SelectListItem> listCarCategory = (from i in db.DEPARTMENTS.ToList()
                                                    select new SelectListItem
                                                    {
                                                        Text = i.DEPARTMENT_NAME,
                                                        Value = i.DEPARTMENT_ID.ToString()
                                                    }).ToList();
            //view'e taşı
            ViewBag.listCarCategoryView = listCarCategory;
            return View("Update_Employee_View", employee);
        }

        //Update Car
        public ActionResult Update_Employee(EMPLOYEES p)
        {
            var employee = db.EMPLOYEES.Find(p.EMPLOYEE_ID);
            var value = db.DEPARTMENTS.Where(k => k.DEPARTMENT_ID == p.DEPARTMENTS.DEPARTMENT_ID).FirstOrDefault();
            if (p.EMAIL == null || p.PASSWORD == null || p.NAME == null || p.SURNAME == null || p.IDENTIFY_NUMBER == null || (p.IS_ACTIV != 0 && p.IS_ACTIV != 1))
            {
                List<SelectListItem> listCarCategory = (from i in db.DEPARTMENTS.ToList()
                                                        select new SelectListItem
                                                        {

                                                            Text = i.DEPARTMENT_NAME,
                                                            Value = i.DEPARTMENT_ID.ToString()
                                                        }).ToList();
                //view'e taşı
                ViewBag.listCarCategoryView = listCarCategory;
                return View("Update_Employee_View");
            }
            employee.DEPARTMENT_ID = value.DEPARTMENT_ID;
            employee.NAME = p.NAME;
            employee.SURNAME = p.SURNAME;
            employee.BIRT_DATE = p.BIRT_DATE;
            employee.IDENTIFY_NUMBER = p.IDENTIFY_NUMBER;
            employee.PASSWORD = p.PASSWORD;
            employee.EMAIL = p.EMAIL;
            employee.IS_ACTIV = p.IS_ACTIV;
            employee.U_DATE = p.U_DATE;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

STORE_APP/STORE_APP/Views/Employees_/Add_Employee.cshtml
@model STORE_APP.Models.Entity.EMPLOYEES
@{
    ViewBag.Title = "Add_Employee";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Add_Employee</h2>

<form class="form-group" method="post">
    <div></div>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- jQuery UI (Including datepicker) -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @* Car Category Id *@
    <div style="margin-top:15px">
        <label>Employee Department</label>
        @Html.DropDownListFor(employee => employee.DEPARTMENTS.DEPARTMENT_ID, (List<SelectListItem>)ViewBag.listCarCategoryView, new { @class = "form-control" })

    </div>
    @* Car Shassis Code *@
    <div style="margin-top:15px">
        <label>Name</label>
        @Html.TextBoxFor(employee => employee.NAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(employee => employee.NAME, "", new { @style = "color:red" })
    </div>
    @* Car Number Plate *@
    <div style="margin-top:15px">
        <label>Surname</label>
        @Html.TextBoxFor(employee => employee.SURNAME, new { @class = "form-control" })
        @Html.ValidationMessageFor(employee => employee.SURNAME, "", new { @style = "color:red" })
    </div>
    @* Activity *@
    <div style="margin-top:15px">
        <label>Birt Date</label>
        <input type="text" id="datepicker" class="form-control" name="BIRT_DATE"
               value="@DateTime.Now.ToShortDateString()" />
        <script>
            $(function () {
                $("#datepicker").datepicker({ dateFormat: "dd/mm/yy" });
            });
        </script>
    </div>
    @* Activity *@
    <div style="margin-top:15px">
        <label>Identity Number</label>
        @Html.TextBoxFor(employee => employee.IDENTIFY_NUMBER, new { @class = "form-control" })
        @Html.ValidationMessageFor(employee => employee.IDENTIFY_NUMBER, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>Password</label>
        @Html.TextBoxFor(employee => employee.PASSWORD, new { @class = "form-control" })
        @Html.ValidationMessageFor(employee => employee.PASSWORD, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>E-Mail</label>
        @Html.TextBoxFor(employee => employee.EMAIL, new { @class = "form-control" })
        @Html.ValidationMessageFor(employee => employee.EMAIL, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <datalist id="Activity">
            <option value="1">
            <option value="0">
        </datalist>
        <label>Activity</label>
        <input type="text" class="form-control" name="IS_ACTIV"
               list="Activity" />
        @Html.ValidationMessageFor(x => x.IS_ACTIV, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <label>C_dATE</label>
        <input type="text" id="datepicker1" class="form-control" name="C_DATE"
               value="@DateTime.Now.ToShortDateString()" />
        <script>
            $(function () {
                $("#datepicker1").datepicker({ dateFormat: "dd/mm/yy" });
            });
        </script>
    </div>
    @* Add Car Button *@
    <div style="margin-top:15px">
        <button class="btn btn-info">Add Employee</button>
    </div>
</form>

STORE_APP/STORE_APP/Views/Employees_/Index.cshtml
@using STORE_APP.Models.Entity
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2><strong>Employees</strong></h2>

@* ActionResult  Controller  *@
@*@using (Html.BeginForm("Index", "Employees_", FormMethod.Get))
    {
        <div style="margin-top;15px; margin-bottom:15px;">
            <b>Aranacak İSMİ girin: &nbsp</b>@Html.TextBox("p")
            <input type="submit" value="Ara"
        </div>
    }*@
<table class="table table-bordered">
    <tr>
        @* Create Table *@
        <th>EMPLOYEE_ID</th>
        <th>Name</th>
        <th>Department Name</th>
        <th>Birt Date</th>
        <th>Identity Number</th>
        <th>Activity</th>
        <th>Password</th>
        <th>E-Mail</th>
        <th>C_DATE</th>
        <th>U_DATE</th>
        <th>Delete</th>
        <th>Update</th>
    </tr>
    @* Get Date *@
    @foreach (var employee in Model)
    {
        <tr>
            @* Get Date For Table *@
            <td>@employee.EMPLOYEE_ID</td>
            <td>@employee.NAME  @employee.SURNAME</td>
            <td>@employee.DEPARTMENTS.DEPARTMENT_NAME</td>
            <td>@Convert.ToDateTime(employee.BIRT_DATE).ToString("dd/MM/yyyy")</td>
            <td>@employee.IDENTIFY_NUMBER</td>
            <td>@employee.IS_ACTIV</td>
            <td>@employee.PASSWORD</td>
            <td>@employee.EMAIL</td>
            <td>@Convert.ToDateTime(employee.C_DATE).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(employee.U_DATE).ToString("dd/MM/yyyy")</td>
            <td>@Html.ActionLink("Delete", "Delete_Employee", new { id = employee.EMPLOYEE_ID }, new { @class = "btn btn-danger", onclick = "return confirm('Do you want delete this department?')" })</td>
            <td><a href="/Employees_/Update_Employee_View/@employee.EMPLOYEE_ID" class="btn btn-success">Update</a></td>
        </tr>
    }
</table>
<a href="/Employees_/Add_Employee/" class="btn btn-primary">Add New Employee</a>

STORE_APP/STORE_APP/Views/Employees_/Update_Employee_View.cshtml
@model STORE_APP.Models.Entity.EMPLOYEES
@{
    ViewBag.Title = "Update_Employee_View";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Update_Employee_View</h2>


@*                  ActionResult        Controller *@
@using (Html.BeginForm("Update_Employee", "Employees_", FormMethod.Post))
{<div></div>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- jQuery UI (Including datepicker) -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @* Car Category Id *@
<div style="margin-top:15px">
    <label>Employee Id</label>
    @Html.TextBoxFor(employee => employee.EMPLOYEE_ID, new { @class = "form-control" })
</div>
<div style="margin-top:15px">
    <label>Employee Department</label>
    @Html.DropDownListFor(employee => employee.DEPARTMENTS.DEPARTMENT_ID, (List<SelectListItem>)ViewBag.listCarCategoryView, new { @class = "form-control" })

</div>
@* Car Shassis Code *@
<div style="margin-top:15px">
    <label>Name</label>
    @Html.TextBoxFor(employee => employee.NAME, new { @class = "form-control" })
    @Html.ValidationMessageFor(employee => employee.NAME, "", new { @style = "color:red" })
</div>
@* Car Number Plate *@
<div style="margin-top:15px">
    <label>Surname</label>
    @Html.TextBoxFor(employee => employee.SURNAME, new { @class = "form-control" })
    @Html.ValidationMessageFor(employee => employee.SURNAME, "", new { @style = "color:red" })
</div>
@* Activity *@
<div style="margin-top:15px">
    <label>Birt Date</label>
    <input type="text" id="datepicker" class="form-control" name="BIRT_DATE"
           value="@DateTime.Now.ToShortDateString()" />
    <script>
        $(function () {
            $("#datepicker").datepicker({ dateFormat: "dd/mm/yy" });
        });
    </script>
</div>
@* Activity *@
<div style="margin-top:15px">
    <label>Identity Number</label>
    @Html.TextBoxFor(employee => employee.IDENTIFY_NUMBER, new { @class = "form-control" })
    @Html.ValidationMessageFor(employee => employee.IDENTIFY_NUMBER, "", new { @style = "color:red" })
</div>
<div style="margin-top:15px">
    <label>Password</label>
    @Html.TextBoxFor(employee => employee.PASSWORD, new { @class = "form-control" })
    @Html.ValidationMessageFor(employee => employee.PASSWORD, "", new { @style = "color:red" })
</div>
<div style="margin-top:15px">
    <label>E-Mail</label>
    @Html.TextBoxFor(employee => employee.EMAIL, new { @class = "form-control" })
    @Html.ValidationMessageFor(employee => employee.EMAIL, "", new { @style = "color:red" })
</div>
<div style="margin-top:15px">
    <datalist id="Activity">
        <option value="1">
        <option value="0">
    </datalist>
    <label>Activity</label>
    <input type="text" class="form-control" name="IS_ACTIV"
           list="Activity" />
    @Html.ValidationMessageFor(x => x.IS_ACTIV, "", new { @style = "color:red" })
</div>
<div style="margin-top:15px">
    <label>U_DATE</label>
    <input type="text" id="datepicker1" class="form-control" name="U_DATE"
           value="@DateTime.Now.ToShortDateString()" />
    <script>
        $(function () {
            $("#datepicker1").datepicker({ dateFormat: "dd/mm/yy" });
        });
    </script>
</div>
<div style="margin-top:15px"><button class="btn btn-warning">Update</button></div>
}